# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: operators
#   namespace: argocd
# spec:
#   goTemplate: true
#   goTemplateOptions: ["missingkey=error"]
#   generators:
#     - git:
#         repoURL: https://github.com/oprimogus/oprimoguslab-gitops.git
#         revision: talos
#         files:
#           - path: "k8s/operators/*/app.yaml"
#   template:
#     metadata:
#       name: '{{ .name }}'
#       namespace: argocd
#     spec:
#       project: operators
#       sources:
#         - repoURL: '{{ .repoURL }}'
#           chart: '{{ .chart }}'
#           targetRevision: '{{ .targetRevision }}'
#           helm:
#             values: |
#               {{- .values | nindent 14 }}
#         - repoURL: 'https://github.com/oprimogus/oprimoguslab-gitops.git'
#           targetRevision: talos
#           path: '{{ .path.path }}/templates'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: '{{ .namespace }}'
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
#         syncOptions:
#           - CreateNamespace=true
#           - ServerSideApply=true
#           - RespectIgnoreDifferences=true
# 
# 
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/oprimogus/oprimoguslab-gitops.git
        revision: talos
        files:
          - path: k8s/operators/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: '{{namespace}}'
    spec:
      project: operators
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        chart: '{{chart}}'
        helm:
          values: |
            {{values}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true 