apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: teamspeak-udp-voice
  namespace: teamspeak
spec:
  entryPoints:
    - teamspeak-voice
  routes:
  - services:
    - name: teamspeak
      port: 9987