apiVersion: v2
name: external-secrets
description: Wrapper chart para o External Secrets Operator
type: application
version: 0.1.0

dependencies:
  - name: external-secrets
    version: 0.15.1
    repository: https://charts.external-secrets.io
    alias: eso