name: traefik
repoURL: https://traefik.github.io/charts
targetRevision: 41.4.0
chart: traefik
namespace: traefik
values: |
  ports:
    web:
      port: 80
      # Se precisar de redirecionamento, na v41 geralmente usa-se redirection:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
    websecure:
      port: 443
      tls:
        enabled: true