name: teamspeak
repoURL: https://oprimogus.github.io/helm-charts
targetRevision: 0.1.6
chart: generic-application
namespace: teamspeak
values: |
    name: teamspeak
    
    image:
      repository: teamspeak
      tag: 3.13.8
      pullPolicy: IfNotPresent
    
    resources:
      min:
        cpu: 1
        memory: 1Gi
      max:
        cpu: 2
        memory: 2Gi
      autoscaling:
        enable: false
    
    env:
      # TS3SERVER_DB_PLUGIN: ts3db_mariadb
      # TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      # TS3SERVER_DB_HOST: db
      # TS3SERVER_DB_USER: root
      # TS3SERVER_DB_PASSWORD: example
      # TS3SERVER_DB_NAME: teamspeak
      # TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    
   
    service:
      enabled: true
      type: ClusterIP
      ports:
        - name: voice
          port: 9987
          targetPort: 9987
          protocol: UDP
        - name: server-query
          port: 10011
          targetPort: 10011
          protocol: TCP
        - name: file-transfer
          port: 30033
          targetPort: 30033
          protocol: TCP

    sidecars:
      - name: playitgg
        
        image:
          repository: ghcr.io/playit-cloud/playit-agent
          tag: 0.16
          pullPolicy: IfNotPresent
        
        resources:
          min:
            cpu: 200m
            memory: 256Mi
          max:
            cpu: 400m
            memory: 512Mi
          autoscaling:
            enable: false
        
        secrets:
          - name: SECRET_KEY
            secret: playitgg
            key: secretKey
      