name: longhorn
repoURL: https://charts.longhorn.io/
chart: longhorn
targetRevision: 1.12.1
namespace: longhorn-system
values: |
  preUpgradeChecker:
    jobEnabled: false
  defaultSettings:
    baseUrl: http://longhorn-backend.longhorn-system.svc.cluster.local:9500