# Configurações passadas diretamente para o Chart dependente (longhorn)
longhorn:
  preUpgradeChecker:
    jobEnabled: false

  defaultSettings:
    baseUrl: http://longhorn-backend.longhorn-system.svc.cluster.local:9500
    defaultDataPath: /var/mnt/longhorn

  csi:
    kubeletRootDir: /var/lib/kubelet