apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-retain