apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cnpg
spec:
  instances: 1
  # Users
  managed:
    roles:
    - name: flyfood-api-prod
      login: true
      # Secret must be "type: kubernetes.io/basic-auth"
      passwordSecret:
        name: flyfood-api-prod-db
    - name: flyfood-api-dev
      login: true
      passwordSecret:
        name: flyfood-api-dev-db
    - name: zitadel
      login: true
      createdb: true
      createrole: true
      passwordSecret:
        name: zitadel-db
  certificates:
    serverTLSSecret: postgres-cluster-cert
    replicationTLSSecret: postgres-cluster-client-cert
    serverCASecret: certs-bundle
    clientCASecret: certs-bundle
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: longhorn-retain
      volumeName: cnpg-cluster-pv
  monitoring:
    enablePodMonitor: true