name: glowly-front
repoURL: https://oprimogus.github.io/helm-charts
targetRevision: 0.1.0
chart: generic-application
namespace: glowly
values: |
    name: glowly-front
    environment: dev

    image:
    repository: ghcr.io/oprimogus/glowly-front-main
    tag: latest
    pullPolicy: Always
    pullSecrets:
        - github-container-registry
    
    resources:
    min:
        cpu: 100m
        memory: 128Mi
    max:
        cpu: 500m
        memory: 256Mi
    autoscaling:
        enable: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
    
    health:
    liveness:
        enabled: true
    readiness:
        enabled: true
    
    
    service:
    enabled: true
    type: ClusterIP
    ports:
        - name: http
        port: 80
        targetPort: 3000
        protocol: TCP
    
    ingress:
    enabled: true
    host: oprimoguslab.xyz
    path: /glowly
