apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazar-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-retain
  volumeName: bazarr-config-pv