apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-config-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-retain
  csi:
    driver: driver.longhorn.io
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "20"
    volumeHandle: pvc-9d8a668f-cbda-4cb3-af52-1c5697a393f2