apiVersion: v1
kind: PersistentVolume
metadata:
  name: cnpg-cluster-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-retain
  csi:
    driver: driver.longhorn.io
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "20"
    volumeHandle: pvc-ac38fdaf-1fa4-49f3-988b-d18af538aa59