apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-config-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-retain
  csi:
    driver: driver.longhorn.io
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "20"
    volumeHandle: pvc-0964fe3d-9718-4dd9-8c67-7d2972859e35