apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-storage
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7200Gi
  storageClassName: nfs-media
  volumeName: nas-media-storage-pv