
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-retain
  csi:
    driver: driver.longhorn.io
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "20"
    volumeHandle: pvc-e5b46815-7dae-4859-a874-47f80ee752b7