apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-s3
  namespace: seaweedfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nas-s3-pv