apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-retain
  csi:
    driver: driver.longhorn.io
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "20"
    volumeHandle: pvc-789b7834-eca4-463c-9c85-7c3a1f90223f