apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-files-storage
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi
  storageClassName: omv-nfs-nextcloud
