name: nfs-subdir-provisioner
repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
targetRevision: 4.0.18
chart: nfs-subdir-external-provisioner
namespace: kube-system
values: |
  nfs:
    server: 192.168.18.146
    path: /export/k8s/
  storageClass:
    name: omv-nfs
    defaultClass: false