apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
  storageClassName: longhorn-retain
