apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-storage
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3727Gi
  storageClassName: omv-nfs
