apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nass-media-storage
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3600Gi
  storageClassName: omv-nfs
