apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-omv-nas
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany # NFS permite que múltiplos pods acessem simultaneamente
  storageClassName: omv-nfs
  resources:
    requests:
      storage: 10Gi
