name: servarr
repoURL: https://charts.kubito.dev
targetRevision: 1.2.2
chart: servarr
namespace: servarr
values: |
    jellyfin:
      image:
        tag: "10.11.6"
      persistence:
        config:
          enabled: true
          existingClaim: "jellyfin-config"
        media:
          enabled: true
          existingClaim: "nas-media-storage"
      service:
        type: NodePort
        port: 8096
        nodePort: "30000"
      ingress:
        enabled: true
        hosts:
          - jellyfin.oprimoguslab.xyz
        path: /
      podSecurityContext:
        fsGroup: 1000
      extraEnvVars:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Sao_Paulo"

    sonarr:
      ingress:
        enabled: true
        hosts:
          - host: sonarr.oprimoguslab.xyz
            paths:
              - path: /
                pathType: Prefix
      persistence:
        enabled: true
        existingClaim: "sonarr-config"
    
    qbittorrent:
      ingress:
        enabled: true
        hosts:
          - host: qbittorrent.oprimoguslab.xyz
            paths:
              - path: /
                pathType: Prefix
      initContainers:
        - name: fix-perms
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1000:1000 /media && chmod -R 775 /media
          volumeMounts:
            - name: media
              mountPath: /media
      persistence:
        enabled: true
        existingClaim: "qbittorrent-config"
        
    prowlarr:
      ingress:
        enabled: true
        hosts:
          - host: prowlarr.oprimoguslab.xyz
            paths:
              - path: /
                pathType: Prefix
      persistence:
        enabled: true
        existingClaim: "prowlarr-config"
        
    jellyseerr:
      image:
        tag: "2.7.3"
      ingress:
        enabled: true
        hosts:
          - host: jellyseerr.oprimoguslab.xyz
            paths:
              - path: /
                pathType: Prefix
      persistence:
        enabled: true
        existingClaim: "jellyseerr-config"
        
    bazarr:
      ingress:
        enabled: true
        hosts:
          - host: bazarr.oprimoguslab.xyz
            paths:
              - path: /
                pathType: Prefix
      persistence:
        enabled: true
        existingClaim: "bazarr-config"
        
    radarr:
      ingress:
        enabled: true
        hosts:
          - host: radarr.oprimoguslab.xyz
            paths:
              - path: /
                pathType: Prefix
      persistence:
        enabled: true
        existingClaim: "radarr-config"
    
    lidarr:
      ingress:
        enabled: true
        hosts:
          - host: lidarr.oprimoguslab.xyz
            paths:
              - path: /
                pathType: Prefix
      persistence:
        existingClaim: "lidarr-config"
    
    flaresolverr:
      ingress:
        enabled: true
        hosts:
          - host: flaresolverr.oprimoguslab.xyz
            paths:
              - path: /
                pathType: Prefix
        
    cleanuparr:
      ingress:
        enabled: true
        hosts:
          - host: cleanuparr.oprimoguslab.xyz
            paths:
              - path: /
                pathType: Prefix
      persistence:
        enabled: true
        existingClaim: "cleanuparr-config"
