apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
spec:
  description: My App Project
  sourceRepos:
    - https://github.com/oprimogus/oprimoguslab-gitops.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: 'Event'